version: '3.3'

services:
  app: 
    build: ./
    container_name: aluracord
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next 
