
services:
  app: 
    build: ./
    container_name: aluracord
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next 
